### ISSUE TITLE
content-type 支持

### ISSUE THREAD

**Issue by timeloveboy** [light4d/lightpan#1]
根据上传文件的后缀名，存储content-type

保证浏览器获取到文件后，能够直接正确显示

**Comment by timeloveboy** [comment]
写入contenttype，参考这里
https://github.com/minio/minio-go/blob/master/core.go#L73

读取contenttype，参考这里
https://github.com/minio/minio-go/blob/master/core.go#L145

**Comment by cashlzcj** [comment]
已解决
